language: csharp

dotnet: 3.1

script:
  - dotnet build dNET.sln -c Release
  - dotnet test -c Release --no-build dNET/Calculator_Tests/Calculator_Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_script:
  - bash <(curl -s https://codecov.io/bash)