language: c
sudo: false # only for faster builds
script:
  - clang -coverage -O0 coverage.xml -o hello
  - ./
  - gcov coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)language: c#
