name: .NET Core

name: .NET Core

on:
push:
branches: '**'
pull_request:
branches: '**'

defaults:
run:
working-directory: ./

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{bb5d6301-45af-4c7d-be91-8a7d195000b6}}
        file: ./Coverages.xml
        flags: unittests
        name: codecov-umbrella
